### ISSUE TITLE
undefined reference to strlcpy on Arch Linux

### ISSUE THREAD

**Issue by Tmplt** [dertuxmalwieder/fileweight#3]
`strlcpy` is undefined on my system with `fileweight.c` as-is. Including `<bsd/string.h>` and linking `-lbsd` makes me able to pass compilation, though.

**Comment by dertuxmalwieder** [comment]
Thank you, I hadn't tested on Linux (as I don't have a Linux machine at hand).

**Comment by dertuxmalwieder** [comment]
I committed a fix, tested on Cygwin.
